In [228]:
import pandas as pd

data_path = '/home/hey/git/DaSEA-Network/data/'
conan_pkg = 'conan/conan_packages_03-05-2022.csv'
alire_pkg = 'alire/alire_packages_03-05-2022.csv'
cargo_pkg = 'cargo/cargo_packages_03-05-2022.csv'
fpm_pkg = 'fpm/fpm_packages_03-05-2022.csv'
nimble_pkg = 'nimble/nimble_packages_03-05-2022.csv'
vcpkg_pkg = 'vcpkg/vcpkg_packages_03-05-2022.csv'
homebrew_pkg = 'homebrew/homebrew_packages_03-05-2022.csv'
freebsd11_pkg = '/ports/freebsd11/freebsd11_packages_03-05-2022.csv'
openbsd69_pkg = 'ports/openbsd69/openbsd69_packages_03-05-2022.csv'

# Remove Freebsd11 prefix
def split_prefix(x):
	return x.split('/')[1]

def _df(path):
    return pd.read_csv(data_path + path)

def _df_ports(path):
    df = _df(path)
    df['name'] = df['name'].apply(split_prefix)
    return df

def difference(df_x, df_y):
    x = set(df_x.name.tolist())
    y = set(df_y.name.tolist())
    return df_x.loc[df_x['name'].isin(x.symmetric_difference(y))]
    
def intersect(df_x, df_y):
    x = set(df_x.name.tolist())
    y = set(df_y.name.tolist())
    return df_x.loc[df_x['name'].isin(x.intersection(y))]

#intersect(_df(vcpkg_pkg), _df_ports(openbsd69_pkg)) 

def check_transitvity(df_a, df_b, df_c):
    # Transitive dependency when A --> B --> C (A has dependency to C)
    not_ac_df = difference(df_a, df_c)
    return not_ac_df
    
check_transitvity(_df(vcpkg_pkg), _)

       idx      name pkgman
4        4       ace  VCPKG
12      12   alembic  VCPKG
25      25       aom  VCPKG
27      27       apr  VCPKG
28      28  apr-util  VCPKG
...    ...       ...    ...
1842  1842        z3  VCPKG
1844  1844    zeromq  VCPKG
1850  1850    zopfli  VCPKG
1852  1852      zstd  VCPKG
1858  1858   zziplib  VCPKG

[310 rows x 3 columns]

In [13]:
import pandas as pd

data_path = '/home/hey/git/DaSEA-Network/data/'
conan_pkg = 'conan/conan_packages_03-05-2022.csv'
conan_dep = 'conan/conan_dependencies_03-05-2022.csv'
freebsd11_pkg = '/ports/freebsd11/freebsd11_packages_03-05-2022.csv'
freebsd11_dep = '/ports/freebsd11/freebsd11_dependencies_03-05-2022.csv'
fpm_pkg = 'fpm/fpm_packages_03-05-2022.csv'
fpm_dep = 'fpm/fpm_dependencies_03-05-2022.csv'
alire_pkg = 'alire/alire_packages_03-05-2022.csv'
alire_dep = 'alire/alire_dependencies_03-05-2022.csv'
cargo_pkg = 'cargo/cargo_packages_03-05-2022.csv'
cargo_dep = 'cargo/cargo_dependencies_03-05-2022.csv'
openbsd69_pkg = 'ports/openbsd69/openbsd69_packages_03-05-2022.csv'
openbsd69_dep = 'ports/openbsd69/openbsd69_dependencies_03-05-2022.csv'
nimble_pkg = 'nimble/nimble_packages_03-05-2022.csv'
nimble_dep = 'nimble/nimble_dependencies_03-05-2022.csv'
vcpkg_pkg = 'vcpkg/vcpkg_packages_03-05-2022.csv'
vcpkg_dep = 'vcpkg/vcpkg_dependencies_03-05-2022.csv'



# Remove Freebsd11 prefix
def split_prefix(x):
	return x.split('/')[1]

def _df(path):
    return pd.read_csv(data_path + path)

def _df_ports(path):
    df = _df(path)
    df['name'] = df['name'].apply(split_prefix)
    return df

def difference(df_x, df_y):
    x = set(df_x.target_name.tolist())
    y = set(df_y.name.tolist())
    return df_x.loc[df_x['target_name'].isin(x.symmetric_difference(y))]

#_df(openbsd69_pkg)

difference(_df(openbsd69_dep),_df(openbsd69_pkg)).tail(10)

#'gnatt' in _df(vcpkg_pkg)

,pkg_idx,source_idx,target_idx,source_name,target_name,source_version,target_version,kind
28547,7417,7417,NaN,x11/yakuake,devel/kf5/kcodecs,NaN,NaN,LIB
28548,7417,7417,NaN,x11/yakuake,devel/kf5/kwidgetsaddons,NaN,NaN,LIB
28549,7417,7417,NaN,x11/yakuake,devel/kf5/kauth,NaN,NaN,LIB
28550,7417,7417,NaN,x11/yakuake,devel/kf5/kcompletion,NaN,NaN,LIB
28551,7417,7417,NaN,x11/yakuake,devel/kf5/kdbusaddons,NaN,NaN,LIB
28552,7417,7417,NaN,x11/yakuake,devel/kf5/extra-cmake-modules,NaN,NaN,BUILD
28553,7417,7417,NaN,x11/yakuake,devel/kf5/kdoctools,NaN,NaN,BUILD
28556,7417,7417,NaN,x11/yakuake,x11/qt5/qttools,NaN,NaN,BUILD
28561,7417,7417,NaN,x11/yakuake,devel/kf5/kdoctools,NaN,NaN,RUN
28563,7417,7417,NaN,x11/yakuake,x11/kde-applications/konsole,NaN,NaN,RUN

In [2]:
difference(_df(conan_dep),_df(conan_pkg)).tail(10)

Empty DataFrame
Columns: [pkg_idx, source_idx, target_idx, source_name, target_name, source_version, target_version, kind, target_version_idx]
Index: []

In [4]:
difference(_df(alire_dep),_df(alire_pkg)).tail(10)

,pkg_idx,source_idx,target_idx,source_name,target_name,source_version,target_version,kind,os_platform
466,238,425,NaN,sparknacl,gnat,3.0.0,>=11.2.1,BUILD,NaN
467,238,426,NaN,sparknacl,gnat,1.0.0,>=2020,BUILD,NaN
468,237,430,NaN,spark_unbound,gnat,0.2.1,(>=9.3.1 & <2000) | >=2021,BUILD,NaN
505,36,448,NaN,bbqueue,gnat,0.1.0,>=10,BUILD,NaN
507,36,449,NaN,bbqueue,gnat,0.3.0,>=10,BUILD,NaN
509,36,450,NaN,bbqueue,gnat,0.2.0,>=10,BUILD,NaN
522,231,456,NaN,shoot_n_loot,gnat,1.0.0,^10,BUILD,NaN
525,28,457,NaN,aws,gnat,21.0.0,>=9,BUILD,NaN
528,219,461,NaN,saatana,gnat,2.0.2,^2020,BUILD,NaN
543,91,477,NaN,iterators,gnat,0.1.0,>=10,BUILD,NaN

In [8]:
difference(_df(cargo_dep),_df(cargo_pkg)).tail(10)

Empty DataFrame
Columns: [pkg_idx, source_idx, target_idx, source_name, target_name, source_version, target_version, kind, optional, target]
Index: []

In [10]:
difference(_df(nimble_dep),_df(nimble_pkg)).tail(10)

,pkg_idx,source_idx,target_idx,source_name,target_name,source_version,target_version,kind
3194,403.0,1892,NaN,progress,nim,1.1.3,>= 0.13.0,BUILD
3195,179.0,1893,NaN,robotparser,nim,1.0,>= 0.18,BUILD
3196,630.0,1894,NaN,gplay,nim,0.1.0,>= 0.17.0,BUILD
3199,861.0,1895,NaN,criterion,https://github.com/disruptek/balls,0.2.8,>= 2.0.0 & < 4.0.0,BUILD
3200,263.0,1896,NaN,nimfuzz,nim,1.3.0,>= 0.10.0,BUILD
3202,573.0,1898,NaN,jack,nim,0.1.0,>= 0.16.0,BUILD
3203,1528.0,1899,NaN,timelog,nim,1.3.0,>= 1.4.0,BUILD
3205,1005.0,1901,NaN,parseini,nim,0.2.0,>= 0.19.0,BUILD
3206,1474.0,1902,NaN,packets,nim,0.4.1,>= 1.4.00,BUILD
3209,1183.0,1903,NaN,asciitype,nim,0.1.0,>= 1.0.2,BUILD

In [14]:
difference(_df(vcpkg_dep),_df(vcpkg_pkg)).tail(10)

Empty DataFrame
Columns: [pkg_idx, source_idx, target_idx, source_name, target_name, source_version, target_version, kind, os_platform]
Index: []

In [12]:
difference(_df(fpm_dep),_df(fpm_pkg)).tail(10)

,pkg_idx,source_idx,target_idx,source_name,target_name,source_version,target_version,kind
2,2,3,NaN,jsonff,erloff,3.0.0,v2.1.0,BUILD
4,2,3,NaN,jsonff,parff,3.0.0,v3.1.4,BUILD
9,12,13,NaN,quaff,erloff,0.4.0,v2.1.0,BUILD
11,12,13,NaN,quaff,parff,0.4.0,v3.1.0,BUILD
13,12,13,NaN,quaff,quaff_asserts,0.4.0,NaN,DEV

In [18]:
difference(_df(freebsd11_dep),_df(freebsd11_pkg)).tail(10)

Empty DataFrame
Columns: [pkg_idx, source_idx, target_idx, source_name, target_name, source_version, target_version, kind]
Index: []